
export const INCOME_CATEGORIES = [
  'SALARY',
  'BUSINESS',
  'FREELANCE',
  'RENTAL INCOME',
  'INTEREST (BANK/FD/RD)',
  'DIVIDENDS',
  'BONUS/INCENTIVES',
  'PENSION',
  'PF',
  'GOVT BENEFITS',
  'OTHER INCOME',
  'INTEREST FROM BANK'
];

export const EXPENSE_STRUCTURE = {
  'HOUSEHOLD & LIVING EXPENSES': [
    'RENT',
    'MAINTENANCE CHARGES',
    'ELECTRICITY BILL',
    'WATER BILL',
    'GAS',
    'INTERNET',
    'MOBILE RECHARGE',
    'OTT RECHARGE',
    'GROCERIES',
    'HOME REPAIRS'
  ],
  'FOOD & DAILY EXPENSES': [
    'VEGETABLES',
    'FRUITS',
    'EATING OUTSIDE',
    'SNACKS'
  ],
  'TRANSPORT & TRAVEL': [
    'PETROL/DIESEL',
    'PUBLIC TRANSPORT',
    'CAB/AUTO',
    'VEHICLE EMI',
    'VEHICLE MAINTANANCE',
    'INSURANCE (VEHICLE)'
  ],
  'PET': [
    'PEDIGREE',
    'CALCIUM BONES',
    'VACCINATION',
    'PET MEDICAL EXP'
  ],
  'ALCOHOL & PARTIES': [
    'ALCOHOL',
    'SMOKES',
    'PARTY FOOD'
  ],
  'CHILDREN/EDUCATION': [
    'SCHOOL / COLLEGE FEES',
    'TUTION / COACHING',
    'BOOKS / STATIONARY',
    'SCHOOL TRANSPORT',
    'UNIFORMS',
    'BBA COURSE FEE',
    'MBA COURSE FEE'
  ],
  'HEALTH / MEDICAL': [
    'DOCTOR CONSULTATION',
    'MEDICINES',
    'LAB TESTS',
    'HEALTH INSURANCE',
    'HOSPITAL EXPENSES'
  ],
  'PERSONAL / FAMILY': [
    'CLOTHING',
    'FOOTWEAR',
    'GROOMING / SALON',
    'RELIGIOUS / TEMPLE EXPENSES',
    'GIFTS / FUNCTIONS',
    'FAMILY SUPPORT'
  ],
  'LOANS / SAVINGS / INVESTMENT': [
    'HOME LOAN EMI',
    'PERSONAL LOAN EMI',
    'CREDIT CARD PAYMENT',
    'SIP / MUTUAL FUNDS',
    'FIXED DEPOSITS / RD',
    'GOLD INVESTMENT',
    'EMERGENCY FUND'
  ],
  'ENTERTAINMENT / LIFESTYLE': [
    'MOVIES',
    'EVENTS',
    'TRIPS',
    'HOBBIES',
    'GYM FEES',
    'HEALTH & WEIGHTLOSS PRODUCTS'
  ],
  'TAXES & PROFESSIONAL': [
    'INCOME TAX',
    'CA / LEGAL FEES'
  ],
  'MISCELLANEOUS': [
    'CHARITY / DONATIONS',
    'FESTIVAL EXPENSES',
    'UNEXPECTED EXPENSES',
    'OTHERS'
  ]
};

export const STORAGE_KEY = 'zen_tracker_transactions_v2';
